### ISSUE TITLE
Error when initiating calculate too fast

### ISSUE THREAD

**Issue by LukasBudach** [jjacobson/ETFCalc#4]
First of all: I'd like to take this one, however can't assign myself, so gotta tell you like this.

I noticed, that when one initates the calculate by pressing the button or enter too fast after filling in the stock symbol an error occurs, due to the data dictionary being empty.

I'd suggest, next to the obvious fix of only do the splicing of data in `` __init__ `` line 58 if data isn't empty, to only enable access to the calculate function once at least one set of data is complete and valid

**Comment by jjacobson** [comment]
Yes, I think the best way to go about his would to set the calculate button to disabled while there are no valid sets of data in the input boxes.

**Comment by jjacobson** [comment]
Addressed in [ac3fcfd](https://github.com/jjacobson/ETFCalc/commit/69a9fad98a082818c62d4dc4c21bf692a40d3d2d) and [b648c1a](https://github.com/jjacobson/ETFCalc/commit/b648c1a87788c15e9cf286856fa12b682ef0fde0)
